name: Deploy to ECR



on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      # boolean:
      #   type: boolean
      #   description: True or False
      choice:
        type: choice
        description: Make a choice
        options:
        - dev
        - prod

 
  push:
    branches: [ develop ]
  # pull_request:
  #   branches:
  #     - master
  #   types: [closed]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    # - name: Check out code
    #   uses: actions/checkout@v2
    
    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-west-1

    # - name: Login to Amazon ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
    #   env:
    #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #     ECR_REPOSITORY: cropped-video-prod
    #     IMAGE_TAG: ${{ github.sha }}
    #     IMAGE_TAG_LATEST: latest

      run: |
       echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }} 
